services:
  db:
    image: postgres:17
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: superkoyomi
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
